name: publish docker image
on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  build-container:
    if: github.repository_owner == 'smilerz'
    name: Build iQbit Container
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.continue-on-error }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          # Standard build config
          - name: Standard
            dockerfile: Dockerfile
            platforms: linux/amd64
            suffix: ""
            continue-on-error: false
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            smilerz/qbit
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          pull: true
          push: true
          platforms: ${{ matrix.platforms }}
          tags: '${{ steps.meta.outputs.tags }}'
          cache-from: type=gha
          cache-to: type=gha,mode=max
